### ISSUE TITLE
[Visual Issue] Delete button

### ISSUE THREAD

**Issue by Woisek** [AlUlkesh/sd_delete_button#2]
As far as I can see, you've added the "Delete prompt" button and made it act as "Delete button". Because this is a duplicate, it is irritating, because the icon _and_ the tooltip implicate that this is a second "Delete prompt". It is necessary to change the icon and the tooltip text. :)

And, when an image is deleted, please consider again deleting possible generated .txt files along with it, like in the image browser.
Good work!

**Comment by Aamir3d** [comment]
The tooltip does say "Delete Prompt", we had another person share this on Reddit.
Good suggestion for the text file.

**Comment by AlUlkesh** [comment]
Interesting. I just searched for a unicode symbol representing a delete operation. I was not aware that webui assigns tooltips by symbol...

Should be fixed now, including the .txt delete.

New delete symbol: ❌
