### ISSUE TITLE
Seems like the latest A1111 update broke the button

### ISSUE THREAD

**Issue by Aamir3d** [AlUlkesh/sd_delete_button#6]
The button doesn't show in the A1111 interface after the 1.6 update.

**Comment by AlUlkesh** [comment]
Thanks. The new version should be able to handle the changed UI elements.

**Comment by DemonAlone** [comment]
Thank you for fast update. It  works now.

**Comment by Aamir3d** [comment]
Thank you for the super quick update. Can confirm it works OK.
